model:
  target: evomerge.CausalLMWithvLLM  # 또는 CausalLMWithTransformers
  params:
    model_path: kooksunho/Merged-Traditional-Chinese-WizardMath
    model_kwargs:
      dtype: bfloat16
    template: zh-alpaca-cot
  
eval:
  target: evomerge.eval.ZhMGSM

