model:
  target: evomerge.CausalLMWithvLLM  # 또는 CausalLMWithTransformers
  params:
    model_path: lchakkei/Mistral-7B-V2-Traditional-Chinese
    model_kwargs:
      dtype: bfloat16
    template: zh-alpaca-cot
  
eval:
  target: evomerge.eval.ZhMGSM

