model:
  target: evomerge.CausalLMWithvLLM  # 또는 CausalLMWithTransformers
  params:
    model_path: mistralai/Mistral-7B-v0.1
    model_kwargs:
      dtype: bfloat16
    template: zh-alpaca-cot
  
eval:
  target: evomerge.eval.ZhMGSM

