model:
  target: evomerge.CausalLMWithvLLM  # 또는 CausalLMWithTransformers
  params:
    model_path: WizardLM/WizardMath-7B-V1.1
    model_kwargs:
      dtype: bfloat16
    template: zh-alpaca-cot
  
eval:
  target: evomerge.eval.ZhMGSM

