model:
  target: evomerge.KoCausalLMWithvLLM  # 또는 CausalLMWithTransformers
  params:
    model_path: WizardLM/WizardMath-7B-V1.1
    model_kwargs:
      dtype: bfloat16
    template: ko-alpaca-cot
  
eval:
  target: evomerge.eval.KoMGSM

