model:
  target: evomerge.KoCausalLMWithvLLM  # 또는 CausalLMWithTransformers
  params:
    model_path: /home/lkk123/komt-mistral-7b-v1
    model_kwargs:
      dtype: bfloat16
    template: ko-alpaca-cot
  
eval:
  target: evomerge.eval.KoMGSM

