model:
  target: evomerge.CausalLMWithvLLM  # 또는 CausalLMWithTransformers
  params:
    model_path: augmxnt/shisa-gamma-7b-v1
    model_kwargs:
      dtype: bfloat16
    template: ja-alpaca-cot
  
eval:
  target: evomerge.eval.JaMGSM

