model:
  target: evomerge.KoCausalLMWithvLLM  # 또는 CausalLMWithTransformers
  params:
    model_path: /home/lkk123/kook/Aitrends_Team2/merged_model/한국어_cma
    model_kwargs:
      dtype: bfloat16
    template: ko-alpaca-cot
  
eval:
  target: evomerge.eval.KoMGSM

